export { IBaseModel } from './ibase-model'
export { IBaseUser } from './ibase-user'
export { IDAO } from './idao'
export { IDefaultAdapterOptions, IRethinkDBConfig } from './idatabase'
export { IPersistController } from './ipersist-controller'
export { IResultSearch } from './iresult-search'
export { ISignupForgot } from './isignup-forgot'
export { ETypePerson, ETypeUser, IPhone, IUser } from './iuser'
